spring.application.name=springChat

server.port=9999

spring.jwt.secret=73bb2537682eaab3ef1dd621cfebbc24afaf8660

spring.datasource.url=jdbc:mysql://localhost:3306/spring_chat
spring.datasource.username=root
spring.datasource.password=1234