spring.application.name=springChat

server.port=9999
server.ssl.enabled=true
server.ssl.key-store=classpath:mycert.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myalias

spring.jwt.secret=73bb2537682eaab3ef1dd621cfebbc24afaf8660
spring.crypto.secret=QUVTLTI1NmNycHl0bzczYmIyNTM3NjgyZWFhYjNlZjFkZDYyMWNmZWJiYzI0YWZhZjg2NjA=
spring.crypto.salt=__NXByMW5nX0NoNDc=

spring.discord.webhook=https://discord.com/api/webhooks/1442409264504242258/SGT1F2yE51snA_iMzCMpEdfkBU4iKATFvO-Tu42CuACttsStp6ZRCseVp7lfK1pWPvKh

spring.datasource.url=jdbc:mysql://localhost:3306/spring_chat
spring.datasource.username=root
spring.datasource.password=1234
